### ISSUE TITLE
Improve the name of the MapReduce jobs submitted by Cloudera ML

### ISSUE THREAD

**Issue by hammer** [cloudera/ml#11]
Currently, the names are like "com.cloudera.science.ml.client.cmd.KMeansSketchCommand: Avro(kdd99)+apply+S0+S1+GBK+combine+S2+Avro(/tmp/crunch-1269388015/p1)	". Would be nice to take the data structure that generates this string and produce something human-readable. Would be especially nice to indicate which iteration we're on during the ksketch command, and how many iterations we plan to do.

**Comment by srowen** [comment]
This project is no longer going to be active, so I'm closing outstanding PRs and issues. Thanks!
