### ISSUE TITLE
Use HADOOP_MAPRED_HOME instead of HADOOP_PREFIX?

### ISSUE THREAD

**Issue by hammer** [cloudera/ml#12]
When using CDH4, we install two versions of Hadoop: 1.x and 2.x. We use HADOOP_PREFIX to point to the 2.x installation, and HADOOP_MAPRED_HOME to point to the 1.x installation. Because Cloudera ML primarily uses MapReduce, I suspect we should be using HADOOP_MAPRED_HOME rather than HADOOP_PREFIX to locate client configuration files.

**Comment by srowen** [comment]
This project is no longer going to be active, so I'm closing outstanding PRs and issues. Thanks!
