### ISSUE TITLE
Add support for arbitrary properties to Vectors

### ISSUE THREAD

**Issue by jwills** [cloudera/ml#14]
Throughtout ML, we use NamedVectors so we can associate an ID with each observation that can be used for later analysis. This ID can be any string we want, but there are often cases where we would want to include an arbitrary number of key-value pairs with a vector as it flowed through a pipeline. We should consider adding a PropertyVector implementation that allows such a structure.

**Comment by srowen** [comment]
This project is no longer going to be active, so I'm closing outstanding PRs and issues. Thanks!
