### ISSUE TITLE
Remedian as a summary statistic

### ISSUE THREAD

**Issue by gcapan** [cloudera/ml#18]
Hi,

An averaging technique called remedian* can approximate median of large datasets without storing whole data. 

Basically, the algorithm needs k b-sized arrays (say medianArray) to store b^k values. It fills the medianArray[0] with first b numbers, stores their median to medianArray[1][0], then sets cursor on medianArray[0] to 0. After medianArray[1] is full, it stores medianArray[1]'s median to medianArray[2][0] cursor on medianArray[1] is set to 0, and so on. 
When median is requested, the algorithm returns:
- If all arrays are full, medianArray[k-1]'s median 
- Else, a weighted median where weight = b^i for each element in ith array.

I have implemented this as an additional summary statistic. I am not very familiar to the library (but tried and liked it), I tried to mimic other computations that are already implemented. InternalNumeric#merge(InternalNumeric) is performed (That does not exist in the paper) by repetitive median updates by values of other's medianArray, where repetition is based on the weight of their indexes calculated as described above.

I tried it on kddcup_data_10_percent (KDD Cup 1999), and a spreadsheet for actual medians and remedians can be found at: https://www.dropbox.com/s/a079iw479c6x81x/kdd99medianvalues.csv

It seems it approximates actual median well most of the time, but there are some columns it failed to result in a good approximation.

If you are interested, the code is in github.com/gcapan/ml. (My fork contains other changes that do not work as expected though, I can create a separate branch if there is an interest)

Best Regards,
Gokhan

*http://web.ipac.caltech.edu/staff/fmasci/home/statistics_refs/Remedian.pdf

**Comment by srowen** [comment]
This project is no longer going to be active, so I'm closing outstanding PRs and issues. Thanks!
