### ISSUE TITLE
ml script should discover hadoop in the path if HADOOP_PREFIX isn't set

### ISSUE THREAD

**Issue by templedf** [cloudera/ml#29]
There are some subtle issues with running MR1 in CDH4/5, and the universal solution seems to be to unset all the environment variables and let the packages discover the correct paths on their own.  Cloudera ML currently forces the use of $HADOOP_PREFIX.

**Comment by srowen** [comment]
This project is no longer going to be active, so I'm closing outstanding PRs and issues. Thanks!
